//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contoso.PartnerPortal.IntegrationTests.ProductCatalogProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://Contoso.LOB.Services/2009/01/BusinessEntities")]
    [System.SerializableAttribute()]
    internal partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SkuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThumbnailImagePathField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryIdField, value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ImagePath {
            get {
                return this.ImagePathField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagePathField, value) != true)) {
                    this.ImagePathField = value;
                    this.RaisePropertyChanged("ImagePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string LongDescription {
            get {
                return this.LongDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.LongDescriptionField, value) != true)) {
                    this.LongDescriptionField = value;
                    this.RaisePropertyChanged("LongDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ShortDescription {
            get {
                return this.ShortDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortDescriptionField, value) != true)) {
                    this.ShortDescriptionField = value;
                    this.RaisePropertyChanged("ShortDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Sku {
            get {
                return this.SkuField;
            }
            set {
                if ((object.ReferenceEquals(this.SkuField, value) != true)) {
                    this.SkuField = value;
                    this.RaisePropertyChanged("Sku");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ThumbnailImagePath {
            get {
                return this.ThumbnailImagePathField;
            }
            set {
                if ((object.ReferenceEquals(this.ThumbnailImagePathField, value) != true)) {
                    this.ThumbnailImagePathField = value;
                    this.RaisePropertyChanged("ThumbnailImagePath");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://Contoso.LOB.Services/2009/01/BusinessEntities")]
    [System.SerializableAttribute()]
    internal partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryIdField, value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ParentId {
            get {
                return this.ParentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentIdField, value) != true)) {
                    this.ParentIdField = value;
                    this.RaisePropertyChanged("ParentId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Part", Namespace="http://Contoso.LOB.Services/2009/01/BusinessEntities")]
    [System.SerializableAttribute()]
    internal partial class Part : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string PartId {
            get {
                return this.PartIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PartIdField, value) != true)) {
                    this.PartIdField = value;
                    this.RaisePropertyChanged("PartId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LOBServicesFault", Namespace="http://schemas.datacontract.org/2004/07/Contoso.LOB.Services.Contracts")]
    [System.SerializableAttribute()]
    internal partial class LOBServicesFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Contoso.LOB.Services/2009/01", ConfigurationName="ProductCatalogProxy.IProductCatalog")]
    internal interface IProductCatalog {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Contoso.LOB.Services/2009/01/IProductCatalog/GetProductSkus", ReplyAction="http://Contoso.LOB.Services/2009/01/IProductCatalog/GetProductSkusResponse")]
        string[] GetProductSkus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Contoso.LOB.Services/2009/01/IProductCatalog/GetProductBySku", ReplyAction="http://Contoso.LOB.Services/2009/01/IProductCatalog/GetProductBySkuResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Contoso.PartnerPortal.IntegrationTests.ProductCatalogProxy.LOBServicesFault), Action="http://Contoso.LOB.Services/2009/01/IProductCatalog/GetProductBySkuLOBServicesFau" +
            "ltFault", Name="LOBServicesFault", Namespace="http://schemas.datacontract.org/2004/07/Contoso.LOB.Services.Contracts")]
        Contoso.PartnerPortal.IntegrationTests.ProductCatalogProxy.Product GetProductBySku(string sku);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Contoso.LOB.Services/2009/01/IProductCatalog/GetProductsByCategory", ReplyAction="http://Contoso.LOB.Services/2009/01/IProductCatalog/GetProductsByCategoryResponse" +
            "")]
        Contoso.PartnerPortal.IntegrationTests.ProductCatalogProxy.Product[] GetProductsByCategory(string categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Contoso.LOB.Services/2009/01/IProductCatalog/GetProducts", ReplyAction="http://Contoso.LOB.Services/2009/01/IProductCatalog/GetProductsResponse")]
        Contoso.PartnerPortal.IntegrationTests.ProductCatalogProxy.Product[] GetProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Contoso.LOB.Services/2009/01/IProductCatalog/GetCategoryById", ReplyAction="http://Contoso.LOB.Services/2009/01/IProductCatalog/GetCategoryByIdResponse")]
        Contoso.PartnerPortal.IntegrationTests.ProductCatalogProxy.Category GetCategoryById(string categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Contoso.LOB.Services/2009/01/IProductCatalog/GetCategories", ReplyAction="http://Contoso.LOB.Services/2009/01/IProductCatalog/GetCategoriesResponse")]
        Contoso.PartnerPortal.IntegrationTests.ProductCatalogProxy.Category[] GetCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Contoso.LOB.Services/2009/01/IProductCatalog/GetChildCategoriesByCategory", ReplyAction="http://Contoso.LOB.Services/2009/01/IProductCatalog/GetChildCategoriesByCategoryR" +
            "esponse")]
        Contoso.PartnerPortal.IntegrationTests.ProductCatalogProxy.Category[] GetChildCategoriesByCategory(string categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Contoso.LOB.Services/2009/01/IProductCatalog/GetPartsByProductSku", ReplyAction="http://Contoso.LOB.Services/2009/01/IProductCatalog/GetPartsByProductSkuResponse")]
        Contoso.PartnerPortal.IntegrationTests.ProductCatalogProxy.Part[] GetPartsByProductSku(string productSku);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    internal interface IProductCatalogChannel : Contoso.PartnerPortal.IntegrationTests.ProductCatalogProxy.IProductCatalog, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    internal partial class ProductCatalogClient : System.ServiceModel.ClientBase<Contoso.PartnerPortal.IntegrationTests.ProductCatalogProxy.IProductCatalog>, Contoso.PartnerPortal.IntegrationTests.ProductCatalogProxy.IProductCatalog {
        
        public ProductCatalogClient() {
        }
        
        public ProductCatalogClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductCatalogClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductCatalogClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductCatalogClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetProductSkus() {
            return base.Channel.GetProductSkus();
        }
        
        public Contoso.PartnerPortal.IntegrationTests.ProductCatalogProxy.Product GetProductBySku(string sku) {
            return base.Channel.GetProductBySku(sku);
        }
        
        public Contoso.PartnerPortal.IntegrationTests.ProductCatalogProxy.Product[] GetProductsByCategory(string categoryId) {
            return base.Channel.GetProductsByCategory(categoryId);
        }
        
        public Contoso.PartnerPortal.IntegrationTests.ProductCatalogProxy.Product[] GetProducts() {
            return base.Channel.GetProducts();
        }
        
        public Contoso.PartnerPortal.IntegrationTests.ProductCatalogProxy.Category GetCategoryById(string categoryId) {
            return base.Channel.GetCategoryById(categoryId);
        }
        
        public Contoso.PartnerPortal.IntegrationTests.ProductCatalogProxy.Category[] GetCategories() {
            return base.Channel.GetCategories();
        }
        
        public Contoso.PartnerPortal.IntegrationTests.ProductCatalogProxy.Category[] GetChildCategoriesByCategory(string categoryId) {
            return base.Channel.GetChildCategoriesByCategory(categoryId);
        }
        
        public Contoso.PartnerPortal.IntegrationTests.ProductCatalogProxy.Part[] GetPartsByProductSku(string productSku) {
            return base.Channel.GetPartsByProductSku(productSku);
        }
    }
}
