//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.SPG.SubSiteCreation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.SPG.SubSiteCreation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred in the Create Sub Site Activity..
        /// </summary>
        internal static string ErrorInCreateSubSiteActivity {
            get {
                return ResourceManager.GetString("ErrorInCreateSubSiteActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto generated by subsite creation service..
        /// </summary>
        internal static string NewSiteDescription {
            get {
                return ResourceManager.GetString("NewSiteDescription", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap NewWebsite {
            get {
                object obj = ResourceManager.GetObject("NewWebsite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The site template or site collection URL properties was not provided..
        /// </summary>
        internal static string NullOrEmptyDependencyProperties {
            get {
                return ResourceManager.GetString("NullOrEmptyDependencyProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred in the Resolve Site Template activity.
        ///ErrorMessage: &apos;{0}&apos;
        ///BusinessEventName: &apos;{1}&apos;
        ///SiteTemplateName: &apos;{2}&apos;
        ///TopSiteRelativeUrl: &apos;{3}&apos;
        ///BusinessEventIdKey: &apos;{4}&apos;.
        /// </summary>
        internal static string ResolveSiteTemplateFaultMessage {
            get {
                return ResourceManager.GetString("ResolveSiteTemplateFaultMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap SearchInFolder {
            get {
                object obj = ResourceManager.GetObject("SearchInFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SychronizeList {
            get {
                object obj = ResourceManager.GetObject("SychronizeList", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
