//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contoso.PartnerPortal.Collaboration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contoso.PartnerPortal.Collaboration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified by Feature Receiver..
        /// </summary>
        internal static string CheckInValue {
            get {
                return ResourceManager.GetString("CheckInValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras metus odio, euismod eu posuere eget, sagittis quis turpis. Ut vestibulum, arcu at gravida porttitor, augue ligula tincidunt libero, vitae malesuada elit magna in tortor. Cras tincidunt eros ac dui vehicula facilisis. Curabitur risus mauris, ullamcorper nec iaculis ac, eleifend vulputate tellus. Fusce pellentesque, nibh nec vestibulum cursus, massa sem malesuada nibh, non iaculis arcu lorem sed tellus. Fusce tempus lacinia velit, ut facilisis m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PageContent {
            get {
                return ResourceManager.GetString("PageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page was auto generated. Update content before publishing..
        /// </summary>
        internal static string PageDescription {
            get {
                return ResourceManager.GetString("PageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras metus odio, euismod eu posuere eget, sagittis quis turpis. Ut vestibulum, arcu at gravida porttitor, augue ligula tincidunt libero, vitae malesuada elit magna in tortor. Cras tincidunt eros ac dui vehicula facilisis. Curabitur risus mauris, ullamcorper nec iaculis ac, eleifend vulputate tellus. Fusce pellentesque, nibh nec vestibulum cursus, massa sem malesuada nibh, non iaculis arcu lorem sed tellus. Fusce tempus lacinia velit, ut facilisis m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PartnerSpecificContent {
            get {
                return ResourceManager.GetString("PartnerSpecificContent", resourceCulture);
            }
        }
    }
}
