//===============================================================================
// Microsoft patterns & practices
// SharePoint Guidance version 2.0
//===============================================================================
// Copyright (c) Microsoft Corporation.  All rights reserved.
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS FOR A PARTICULAR PURPOSE.
//===============================================================================
// The example companies, organizations, products, domain names,
// e-mail addresses, logos, people, places, and events depicted
// herein are fictitious.  No association with any real company,
// organization, product, domain name, email address, logo, person,
// places, or events is intended or should be inferred.
//===============================================================================
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Contoso.PartnerPortal.PartnerDirectory
{
    public static class Constants
    {
        public const string PartnerSiteDirectoryUrlConfigKey = "Contoso.PartnerPortal.PartnerCentral.ConfigSettings.partnerSiteDirectoryUrl";
        public const string PageContentTypeId = "0x010100C568DB52D9D0A14D9B2FDCC96666E9F2007948130EC3DB064584E219954237AF390010630EDF2D1DBE4087C85E548EA192E0";
        public const string TitleFieldId = "fa564e0f-0c70-4ab9-b863-0177e6ddd247";
        public const string SitesList = "Sites";
        public const string TitlewURL = "TitlewURL";
        public const string PartnerDirectoryPartnerField = "PartnerDirectoryPartnerField";
        public const string QueryForPartnerSites = "<And><Where><Neq><FieldRef Name=\"PartnerDirectoryPartnerField\"/><Value Type=\"Text\"></Value></Neq></Where></And>";
        public const string PartnerSitesView = "PartnerSites";
        public const string PartnerSitesPageUrl = "Pages/partnersites.aspx";
        public const string TopSitesPageUrl = "Pages/topsites.aspx";
        public const string PartnerSitesFileName = "partnersites.aspx";
        public const string PartnerSitesTile = "Partner Sites";
        public const string DescriptionField = "Description";
        public const string LeftColumnZone = "LeftColumnZone";
        public const string CheckInComment = "Page was autogenerated by Contoso Partner Site Directory Feature.";
        public const string TabsList = "Tabs";
        public const string TabNameField = "Tab Name";
        public const string PartnersTabName = "Partners";
        public const string PageField = "Page";
        public const string TooltipField = "Tooltip";
        public const string PartnerSitesTooltip = "Click for partner sites";
        public const string PartnerDirectoryRelativeUrl = "/sites/partnercentral/partnerdirectory";
    }
}
