//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contoso.PartnerPortal.Services.IncidentSite {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Contoso.PartnerPortal.Services/2009/01", ConfigurationName="Contoso.PartnerPortal.Services.IncidentSite.IIncidentSite")]
    public interface IIncidentSite {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Contoso.PartnerPortal.Services/2009/01/IIncidentSite/UpdateIncidentStatus", ReplyAction="http://Contoso.PartnerPortal.Services/2009/01/IIncidentSite/UpdateIncidentStatusR" +
            "esponse")]
        void UpdateIncidentStatus(string incidentId, string partner, string status);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IIncidentSiteChannel : Contoso.PartnerPortal.Services.IncidentSite.IIncidentSite, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class IncidentSiteClient : System.ServiceModel.ClientBase<Contoso.PartnerPortal.Services.IncidentSite.IIncidentSite>, Contoso.PartnerPortal.Services.IncidentSite.IIncidentSite {
        
        public IncidentSiteClient() {
        }
        
        public IncidentSiteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IncidentSiteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IncidentSiteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IncidentSiteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void UpdateIncidentStatus(string incidentId, string partner, string status) {
            base.Channel.UpdateIncidentStatus(incidentId, partner, status);
        }
    }
}
