//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contoso.PartnerPortal.Services.SubSiteCreation {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Contoso.PartnerPortal.Services/2009/01", ConfigurationName="Contoso.PartnerPortal.Services.SubSiteCreation.ISubSiteCreation")]
    public interface ISubSiteCreation {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Contoso.PartnerPortal.Services/2009/01/ISubSiteCreation/CreateSubSite", ReplyAction="http://Contoso.PartnerPortal.Services/2009/01/ISubSiteCreation/CreateSubSiteRespo" +
            "nse")]
        void CreateSubSite(string businessEvent, string eventIdentifier, string entityId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ISubSiteCreationChannel : Contoso.PartnerPortal.Services.SubSiteCreation.ISubSiteCreation, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SubSiteCreationClient : System.ServiceModel.ClientBase<Contoso.PartnerPortal.Services.SubSiteCreation.ISubSiteCreation>, Contoso.PartnerPortal.Services.SubSiteCreation.ISubSiteCreation {
        
        public SubSiteCreationClient() {
        }
        
        public SubSiteCreationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SubSiteCreationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubSiteCreationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubSiteCreationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreateSubSite(string businessEvent, string eventIdentifier, string entityId) {
            base.Channel.CreateSubSite(businessEvent, eventIdentifier, entityId);
        }
    }
}
