//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.SPG.AJAXSupport.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.SPG.AJAXSupport.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;add assembly=&quot;System.Web.Extensions, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35&quot; /&gt;.
        /// </summary>
        internal static string WebConfigModAssemblies {
            get {
                return ResourceManager.GetString("WebConfigModAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;controls&gt;
        ///      &lt;add tagPrefix=&quot;asp&quot; namespace=&quot;System.Web.UI&quot; assembly=&quot;System.Web.Extensions, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35&quot; /&gt;
        ///    &lt;/controls&gt;.
        /// </summary>
        internal static string WebConfigModControls {
            get {
                return ResourceManager.GetString("WebConfigModControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;add verb=&quot;*&quot; path=&quot;*_AppService.axd&quot; validate=&quot;false&quot; type=&quot;System.Web.Script.Services.ScriptHandlerFactory, System.Web.Extensions, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35&quot; /&gt;.
        /// </summary>
        internal static string WebConfigModHttpHandlersAppService {
            get {
                return ResourceManager.GetString("WebConfigModHttpHandlersAppService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;add verb=&quot;*&quot; path=&quot;*.asmx&quot; validate=&quot;false&quot; type=&quot;System.Web.Script.Services.ScriptHandlerFactory, System.Web.Extensions, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35&quot; /&gt;.
        /// </summary>
        internal static string WebConfigModHttpHandlersASMX {
            get {
                return ResourceManager.GetString("WebConfigModHttpHandlersASMX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;add name=&quot;ScriptModule&quot; type=&quot;System.Web.Handlers.ScriptModule, System.Web.Extensions, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35&quot; /&gt;.
        /// </summary>
        internal static string WebConfigModHttpHandlerScriptModule {
            get {
                return ResourceManager.GetString("WebConfigModHttpHandlerScriptModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;add verb=&quot;GET,HEAD&quot; path=&quot;ScriptResource.axd&quot; type=&quot;System.Web.Handlers.ScriptResourceHandler, System.Web.Extensions, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35&quot; validate=&quot;false&quot; /&gt;.
        /// </summary>
        internal static string WebConfigModHttpHandlerScriptResource {
            get {
                return ResourceManager.GetString("WebConfigModHttpHandlerScriptResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SafeControl Assembly=&quot;System.Web.Extensions, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35&quot; Namespace=&quot;System.Web.UI&quot; TypeName=&quot;*&quot; Safe=&quot;True&quot; /&gt;.
        /// </summary>
        internal static string WebConfigModSafeControl {
            get {
                return ResourceManager.GetString("WebConfigModSafeControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;sectionGroup name=&quot;system.web.extensions&quot; type=&quot;System.Web.Configuration.SystemWebExtensionsSectionGroup, System.Web.Extensions, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35&quot;&gt;
        ///      &lt;sectionGroup name=&quot;scripting&quot; type=&quot;System.Web.Configuration.ScriptingSectionGroup, System.Web.Extensions, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35&quot;&gt;
        ///        &lt;section name=&quot;scriptResourceHandler&quot; type=&quot;System.Web.Configuration.ScriptingScriptResourceHandlerSection, System.Web.Ext [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebConfigModSectionGroup {
            get {
                return ResourceManager.GetString("WebConfigModSectionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;system.web.extensions&gt;
        ///      &lt;scripting&gt;
        ///        &lt;webServices&gt;
        ///          &lt;!-- Uncomment this line to enable the authentication service. Include requireSSL=&quot;true&quot; if appropriate. --&gt;
        ///          &lt;!--
        ///        &lt;authenticationService enabled=&quot;true&quot; requireSSL = &quot;true|false&quot;/&gt;
        ///      --&gt;
        ///          &lt;!-- Uncomment these lines to enable the profile service. To allow profile properties to be retrieved and modified in ASP.NET AJAX applications, you need to add each property name to the readAccessProperties and w [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebConfigModSystemWebExtensions {
            get {
                return ResourceManager.GetString("WebConfigModSystemWebExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;system.webServer&gt;
        ///      &lt;validation validateIntegratedModeConfiguration=&quot;false&quot; /&gt;
        ///      &lt;modules&gt;
        ///        &lt;add name=&quot;ScriptModule&quot; preCondition=&quot;integratedMode&quot; type=&quot;System.Web.Handlers.ScriptModule, System.Web.Extensions, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35&quot; /&gt;
        ///      &lt;/modules&gt;
        ///      &lt;handlers&gt;
        ///        &lt;remove name=&quot;WebServiceHandlerFactory-Integrated&quot; /&gt;
        ///        &lt;add name=&quot;ScriptHandlerFactory&quot; verb=&quot;*&quot; path=&quot;*.asmx&quot; preCondition=&quot;integratedMode&quot; type=&quot;System.Web.Sc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebConfigModSystemWebServer {
            get {
                return ResourceManager.GetString("WebConfigModSystemWebServer", resourceCulture);
            }
        }
    }
}
