//===============================================================================
// Microsoft patterns & practices
// SharePoint Guidance version 2.0
//===============================================================================
// Copyright (c) Microsoft Corporation.  All rights reserved.
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS FOR A PARTICULAR PURPOSE.
//===============================================================================
// The example companies, organizations, products, domain names,
// e-mail addresses, logos, people, places, and events depicted
// herein are fictitious.  No association with any real company,
// organization, product, domain name, email address, logo, person,
// places, or events is intended or should be inferred.
//===============================================================================
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnerPortalBVT
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using Microsoft.VisualStudio.TestTools.WebTesting.Rules;
    using PartnerPortalBVT.Settings;

    /// <summary>
    /// This test case browse the portal and navigate to Partner collaboration sites page
    /// verify Partner collaboration sites title exists
    /// </summary>
    public class VerifyPartnerCollaborationSitesPage : WebTest
    {

        string hostURL = CustConfig.GetHostURL;
        public VerifyPartnerCollaborationSitesPage()
        {
            this.PreAuthenticate = true;
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            

            WebTestRequest request1 = new WebTestRequest(hostURL);
            request1.ThinkTime = 4;
            request1.ExpectedResponseUrl = hostURL+"/Pages/Default.aspx";
            yield return request1;
            request1 = null;

            WebTestRequest request2 = new WebTestRequest(hostURL+"/PartnerCollaborationSites");
            request2.ExpectedResponseUrl = hostURL+"/PartnerCollaborationSites/default.aspx";
           
                ValidationRuleFindText validationRule21 = new ValidationRuleFindText();
                validationRule21.FindText = "Partner Collaboration Sites";
                validationRule21.IgnoreCase = true;
                validationRule21.UseRegularExpression = true;
                validationRule21.PassIfTextFound = true;
                request2.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule21.Validate);
           
            yield return request2;
            request2 = null;
        }
    }
}
