//===============================================================================
// Microsoft patterns & practices
// SharePoint Guidance version 2.0
//===============================================================================
// Copyright (c) Microsoft Corporation.  All rights reserved.
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS FOR A PARTICULAR PURPOSE.
//===============================================================================
// The example companies, organizations, products, domain names,
// e-mail addresses, logos, people, places, and events depicted
// herein are fictitious.  No association with any real company,
// organization, product, domain name, email address, logo, person,
// places, or events is intended or should be inferred.
//===============================================================================
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSSBVT
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using Microsoft.VisualStudio.TestTools.WebTesting.Rules;
    using PSSBVT.Settings;

    /// <summary>
    /// This Test Case is browse partner1 site and incident dashboard homepage, verify all webparts are loaded correctly
    /// </summary>
    public class VerifyPartner1IncidentHomePage : WebTest
    {
        string hostURL = CustConfig.GetHostURL;
        public VerifyPartner1IncidentHomePage()
        {
            this.PreAuthenticate = true;
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {


            WebTestRequest request1 = new WebTestRequest(hostURL +"/sites/partner1");
            request1.ExpectedResponseUrl = hostURL +"/sites/partner2/Pages/default.aspx";

            ValidationRuleFindText validationRule3 = new ValidationRuleFindText();
            validationRule3.FindText = "Incident Dashboard";
            validationRule3.IgnoreCase = true;
            validationRule3.UseRegularExpression = true;
            validationRule3.PassIfTextFound = true;
            request1.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule3.Validate);

            yield return request1;
            request1 = null;

            WebTestRequest request2 = new WebTestRequest(hostURL +"/sites/partner1/IncidentDashboard.aspx");
            
                ValidationRuleFindText validationRule21 = new ValidationRuleFindText();
                validationRule21.FindText = "Active Incidents";
                validationRule21.IgnoreCase = true;
                validationRule21.UseRegularExpression = true;
                validationRule21.PassIfTextFound = true;
                request2.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule21.Validate);
            
                ValidationRuleFindText validationRule22 = new ValidationRuleFindText();
                validationRule22.FindText = "Closed Incidents";
                validationRule22.IgnoreCase = true;
                validationRule22.UseRegularExpression = true;
                validationRule22.PassIfTextFound = true;
                request2.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule22.Validate);
           
                ValidationRuleFindText validationRule23 = new ValidationRuleFindText();
                validationRule23.FindText = "Active Incident Tasks";
                validationRule23.IgnoreCase = true;
                validationRule23.UseRegularExpression = false;
                validationRule23.PassIfTextFound = true;
                request2.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule23.Validate);
           
            yield return request2;
            request2 = null;
                      
         }
    }
}
